name: dio_curl_logger
description: "A Flutter package for logging Dio HTTP requests as curl commands and responses, enabling easier debugging and analysis of network interactions."
version: 1.2.0
homepage: https://github.com/Davud44/dio_curl_logger
repository: https://github.com/Davud44/dio_curl_logger

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

example:
  path: example/
